<?php
return [
    'nav.devices' => 'Devices',
    'nav.settings' => 'Settings',
    'nav.logout' => 'Sign out',

    'auth.username' => 'Username',
    'auth.password' => 'Password',
    'auth.login' => 'Sign in',
    'auth.register' => 'Register',
    'auth.device_login' => 'Device sign-in …',
    'auth.err_username' => 'Invalid username (3–32: a–z 0–9 . _ -)',
    'auth.err_password' => 'Password too short (min. 10)',
    'auth.err_exists' => 'Name taken',
    'auth.err_server' => 'Internal error',
    'auth.err_login' => 'Sign-in failed',
    'auth.err_rate' => 'Too many attempts',

    'g.contacts' => 'Contacts',
    'g.health' => 'Health',
    'g.security' => 'Security',
    'g.misc' => 'More',

    'cat.contacts' => 'Contacts',
    'cat.phones' => 'Numbers',
    'cat.heart' => 'Heart',
    'cat.weight' => 'Weight',
    'cat.height' => 'Height',
    'cat.steps' => 'Steps',
    'cat.sleep' => 'Sleep',
    'cat.temp' => 'Temperature',
    'cat.medical' => 'Medical',
    'cat.passwords' => 'Passwords',
    'cat.certs' => 'Licenses',
    'cat.serials' => 'Serials',
    'cat.documents' => 'Documents',
    'cat.notes' => 'Notes',

    'f.name' => 'Name',
    'f.relation' => 'Relation',
    'f.birthdate' => 'Birthdate',
    'f.number' => 'Number',
    'f.blood' => 'Blood type',
    'f.note' => 'Note',
    'f.label' => 'Label',
    'f.date' => 'Date',
    'f.service' => 'Service',
    'f.username' => 'Username',
    'f.password' => 'Password',
    'f.mfa' => 'MFA/2FA',
    'f.device' => 'Device',
    'f.serial' => 'Serial number',
    'f.title' => 'Title',

    'a.new' => 'New',
    'a.value' => 'Value',
    'a.save' => 'Save',
    'a.delete' => 'Delete',
    'a.archive' => 'Old',
    'a.restore' => 'Active',
    'a.old' => 'Old',
    'a.me' => 'Me',
    'a.back' => 'Back',
    'a.saved' => 'Saved',
    'a.empty' => 'Empty',
    'a.name' => 'Name',

    's.latest' => 'Latest',
    's.avg' => 'Avg',
    's.min' => 'Min',
    's.max' => 'Max',

    'd.token_once' => 'Token is shown only once',
    'd.current' => 'this device',
    'd.apikey' => 'API key',

    'st.pw_old' => 'Current password',
    'st.pw_new' => 'New password',

    'i.title' => 'Install as app',
    'i.ios_1' => 'Safari: tap Share',
    'i.ios_2' => '"Add to Home Screen"',
    'i.ios_3' => 'Launch from home screen',
    'i.android_1' => 'Chrome: tap menu ⋮',
    'i.android_2' => '"Install app"',
    'i.android_3' => 'Launch from home screen',
    'i.other' => 'Open on your phone and add to home screen',

    'err.value' => 'Invalid value',
    'err.date' => 'Invalid date',
    'err.empty' => 'Empty',
    'a.edit' => 'Edit',
    'a.cancel' => 'Cancel',
    'a.search' => 'Search',
    'a.copy' => 'Copy',
    'a.sure' => 'Really delete?',
    'r.7' => '7d',
    'r.30' => '30d',
    'r.90' => '90d',
    'r.365' => '1y',
    'r.all' => 'All',
    'r.empty' => 'No values in this range',
    'st.export' => 'Export data',
    'st.import' => 'Import',
    'st.import_sure' => 'Replace all entries with this import?',
    'err.import' => 'Invalid file',
    'i.continue' => 'continue in browser',
    'nav.home' => 'Overview',
    'st.lang' => 'Language',
    'st.delaccount' => 'Delete account',
    'st.delaccount_sure' => 'Permanently delete account and ALL data?',
];
