<?php
return [
    'nav.devices' => 'Geräte',
    'nav.settings' => 'Einstellungen',
    'nav.logout' => 'Abmelden',

    'auth.username' => 'Benutzername',
    'auth.password' => 'Passwort',
    'auth.login' => 'Anmelden',
    'auth.register' => 'Registrieren',
    'auth.device_login' => 'Geräteanmeldung …',
    'auth.err_username' => 'Ungültiger Benutzername (3–32: a–z 0–9 . _ -)',
    'auth.err_password' => 'Passwort zu kurz (min. 10)',
    'auth.err_exists' => 'Name vergeben',
    'auth.err_server' => 'Interner Fehler',
    'auth.err_login' => 'Anmeldung fehlgeschlagen',
    'auth.err_rate' => 'Zu viele Versuche',

    'a.new' => 'Neu',
    'a.newcat' => 'Neue Kategorie',
    'a.name' => 'Name',
    'a.unit' => 'Einheit',
    'a.field' => 'Feld',
    'a.records' => 'Einträge',
    'a.series' => 'Messreihe',
    'a.value' => 'Wert',
    'a.time' => 'Zeit',
    'a.save' => 'Speichern',
    'a.delete' => 'Löschen',
    'a.archive' => 'Alt',
    'a.restore' => 'Aktiv',
    'a.old' => 'Alt',
    'a.back' => 'Zurück',
    'a.saved' => 'Gespeichert',
    'a.empty' => 'Leer',
    'a.delcat' => 'Kategorie löschen',

    's.latest' => 'Aktuell',
    's.avg' => 'Schnitt',
    's.min' => 'Min',
    's.max' => 'Max',

    'd.token_once' => 'Token wird nur einmal angezeigt',
    'd.current' => 'dieses Gerät',
    'd.apikey' => 'API-Schlüssel',

    'st.pw_old' => 'Aktuelles Passwort',
    'st.pw_new' => 'Neues Passwort',

    'i.title' => 'Als App installieren',
    'i.ios_1' => 'Safari: Teilen antippen',
    'i.ios_2' => '„Zum Home-Bildschirm"',
    'i.ios_3' => 'Vom Home-Bildschirm starten',
    'i.android_1' => 'Chrome: Menü ⋮ antippen',
    'i.android_2' => '„App installieren"',
    'i.android_3' => 'Vom Startbildschirm starten',
    'i.other' => 'Am Handy öffnen und zum Startbildschirm hinzufügen',

    'ft.text' => 'Text',
    'ft.number' => 'Zahl',
    'ft.date' => 'Datum',
    'ft.phone' => 'Telefon',
    'ft.note' => 'Notiz',

    'cat.profile' => 'Profil',
    'cat.people' => 'Menschen',
    'cat.phones' => 'Nummern',
    'cat.heart' => 'Herz',
    'cat.weight' => 'Gewicht',
    'cat.height' => 'Größe',
    'cat.steps' => 'Schritte',
    'cat.sleep' => 'Schlaf',
    'cat.temp' => 'Temperatur',
    'cat.medical' => 'Medizin',
    'cat.documents' => 'Dokumente',
    'cat.notes' => 'Notizen',
    'cat.custom' => 'Kategorie',

    'f.name' => 'Name',
    'f.birthdate' => 'Geburtsdatum',
    'f.blood' => 'Blutgruppe',
    'f.relation' => 'Beziehung',
    'f.number' => 'Nummer',
    'f.label' => 'Bezeichnung',
    'f.date' => 'Datum',
    'f.note' => 'Notiz',
    'f.title' => 'Titel',

    'err.name' => 'Ungültiger Name',
    'err.kind' => 'Ungültige Art',
    'err.fields' => 'Feld fehlt',
    'err.value' => 'Ungültiger Wert',
    'err.date' => 'Ungültiges Datum',
    'err.empty' => 'Leer',
];
