<?php
return [
    'nav.devices' => 'Geräte',
    'nav.settings' => 'Einstellungen',
    'nav.logout' => 'Abmelden',

    'auth.username' => 'Benutzername',
    'auth.password' => 'Passwort',
    'auth.login' => 'Anmelden',
    'auth.register' => 'Registrieren',
    'auth.device_login' => 'Geräteanmeldung …',
    'auth.err_username' => 'Ungültiger Benutzername (3–32: a–z 0–9 . _ -)',
    'auth.err_password' => 'Passwort zu kurz (min. 10)',
    'auth.err_exists' => 'Name vergeben',
    'auth.err_server' => 'Interner Fehler',
    'auth.err_login' => 'Anmeldung fehlgeschlagen',
    'auth.err_rate' => 'Zu viele Versuche',

    'g.contacts' => 'Kontakte',
    'g.health' => 'Gesundheit',
    'g.security' => 'Sicherheit',
    'g.misc' => 'Mehr',

    'cat.contacts' => 'Kontakte',
    'cat.phones' => 'Nummern',
    'cat.heart' => 'Herz',
    'cat.weight' => 'Gewicht',
    'cat.height' => 'Größe',
    'cat.steps' => 'Schritte',
    'cat.sleep' => 'Schlaf',
    'cat.temp' => 'Temperatur',
    'cat.medical' => 'Medizin',
    'cat.passwords' => 'Passwörter',
    'cat.certs' => 'Lizenzen',
    'cat.serials' => 'Seriennummern',
    'cat.documents' => 'Dokumente',
    'cat.notes' => 'Notizen',

    'f.name' => 'Name',
    'f.relation' => 'Beziehung',
    'f.birthdate' => 'Geburtsdatum',
    'f.number' => 'Nummer',
    'f.blood' => 'Blutgruppe',
    'f.note' => 'Notiz',
    'f.label' => 'Bezeichnung',
    'f.date' => 'Datum',
    'f.service' => 'Dienst',
    'f.username' => 'Benutzername',
    'f.password' => 'Passwort',
    'f.mfa' => 'MFA/2FA',
    'f.device' => 'Gerät',
    'f.serial' => 'Seriennummer',
    'f.title' => 'Titel',

    'a.new' => 'Neu',
    'a.value' => 'Wert',
    'a.save' => 'Speichern',
    'a.delete' => 'Löschen',
    'a.archive' => 'Alt',
    'a.restore' => 'Aktiv',
    'a.old' => 'Alt',
    'a.me' => 'Ich',
    'a.back' => 'Zurück',
    'a.saved' => 'Gespeichert',
    'a.empty' => 'Leer',
    'a.name' => 'Name',

    's.latest' => 'Aktuell',
    's.avg' => 'Schnitt',
    's.min' => 'Min',
    's.max' => 'Max',

    'd.token_once' => 'Token wird nur einmal angezeigt',
    'd.current' => 'dieses Gerät',
    'd.apikey' => 'API-Schlüssel',

    'st.pw_old' => 'Aktuelles Passwort',
    'st.pw_new' => 'Neues Passwort',

    'i.title' => 'Als App installieren',
    'i.ios_1' => 'Safari: Teilen antippen',
    'i.ios_2' => '„Zum Home-Bildschirm"',
    'i.ios_3' => 'Vom Home-Bildschirm starten',
    'i.android_1' => 'Chrome: Menü ⋮ antippen',
    'i.android_2' => '„App installieren"',
    'i.android_3' => 'Vom Startbildschirm starten',
    'i.other' => 'Am Handy öffnen und zum Startbildschirm hinzufügen',

    'err.value' => 'Ungültiger Wert',
    'err.date' => 'Ungültiges Datum',
    'err.empty' => 'Leer',
    'a.edit' => 'Bearbeiten',
    'a.cancel' => 'Abbrechen',
    'a.search' => 'Suchen',
    'a.copy' => 'Kopieren',
    'a.sure' => 'Wirklich löschen?',
    'r.7' => '7T',
    'r.30' => '30T',
    'r.90' => '90T',
    'r.365' => '1J',
    'r.all' => 'Alle',
    'r.empty' => 'Keine Werte im Zeitraum',
    'st.export' => 'Daten exportieren',
    'st.import' => 'Import',
    'st.import_sure' => 'Alle Einträge durch den Import ersetzen?',
    'err.import' => 'Ungültige Datei',
    'i.continue' => 'weiter im Browser',
    'nav.home' => 'Übersicht',
    'st.lang' => 'Sprache',
];
