<?php
return [
    'nav.devices' => 'Devices',
    'nav.settings' => 'Settings',
    'nav.logout' => 'Sign out',

    'auth.username' => 'Username',
    'auth.password' => 'Password',
    'auth.login' => 'Sign in',
    'auth.register' => 'Register',
    'auth.device_login' => 'Device sign-in …',
    'auth.err_username' => 'Invalid username (3–32: a–z 0–9 . _ -)',
    'auth.err_password' => 'Password too short (min. 10)',
    'auth.err_exists' => 'Name taken',
    'auth.err_server' => 'Internal error',
    'auth.err_login' => 'Sign-in failed',
    'auth.err_rate' => 'Too many attempts',

    'a.new' => 'New',
    'a.newcat' => 'New category',
    'a.name' => 'Name',
    'a.unit' => 'Unit',
    'a.field' => 'Field',
    'a.records' => 'Records',
    'a.series' => 'Series',
    'a.value' => 'Value',
    'a.time' => 'Time',
    'a.save' => 'Save',
    'a.delete' => 'Delete',
    'a.archive' => 'Old',
    'a.restore' => 'Active',
    'a.old' => 'Old',
    'a.back' => 'Back',
    'a.saved' => 'Saved',
    'a.empty' => 'Empty',
    'a.delcat' => 'Delete category',

    's.latest' => 'Latest',
    's.avg' => 'Avg',
    's.min' => 'Min',
    's.max' => 'Max',

    'd.token_once' => 'Token is shown only once',
    'd.current' => 'this device',
    'd.apikey' => 'API key',

    'st.pw_old' => 'Current password',
    'st.pw_new' => 'New password',

    'i.title' => 'Install as app',
    'i.ios_1' => 'Safari: tap Share',
    'i.ios_2' => '"Add to Home Screen"',
    'i.ios_3' => 'Launch from home screen',
    'i.android_1' => 'Chrome: tap menu ⋮',
    'i.android_2' => '"Install app"',
    'i.android_3' => 'Launch from home screen',
    'i.other' => 'Open on your phone and add to home screen',

    'ft.text' => 'Text',
    'ft.number' => 'Number',
    'ft.date' => 'Date',
    'ft.phone' => 'Phone',
    'ft.note' => 'Note',

    'cat.profile' => 'Profile',
    'cat.people' => 'People',
    'cat.phones' => 'Numbers',
    'cat.heart' => 'Heart',
    'cat.weight' => 'Weight',
    'cat.height' => 'Height',
    'cat.steps' => 'Steps',
    'cat.sleep' => 'Sleep',
    'cat.temp' => 'Temperature',
    'cat.medical' => 'Medical',
    'cat.documents' => 'Documents',
    'cat.notes' => 'Notes',
    'cat.custom' => 'Category',

    'f.name' => 'Name',
    'f.birthdate' => 'Birthdate',
    'f.blood' => 'Blood type',
    'f.relation' => 'Relation',
    'f.number' => 'Number',
    'f.label' => 'Label',
    'f.date' => 'Date',
    'f.note' => 'Note',
    'f.title' => 'Title',

    'err.name' => 'Invalid name',
    'err.kind' => 'Invalid kind',
    'err.fields' => 'Field missing',
    'err.value' => 'Invalid value',
    'err.date' => 'Invalid date',
    'err.empty' => 'Empty',
];
