<?php
return [
    'nav.devices' => 'อุปกรณ์',
    'nav.settings' => 'ตั้งค่า',
    'nav.logout' => 'ออกจากระบบ',

    'auth.username' => 'ชื่อผู้ใช้',
    'auth.password' => 'รหัสผ่าน',
    'auth.login' => 'เข้าสู่ระบบ',
    'auth.register' => 'สมัครสมาชิก',
    'auth.device_login' => 'เข้าสู่ระบบด้วยอุปกรณ์ …',
    'auth.err_username' => 'ชื่อผู้ใช้ไม่ถูกต้อง (3–32: a–z 0–9 . _ -)',
    'auth.err_password' => 'รหัสผ่านสั้นเกินไป (อย่างน้อย 10)',
    'auth.err_exists' => 'ชื่อนี้ถูกใช้แล้ว',
    'auth.err_server' => 'ข้อผิดพลาดภายใน',
    'auth.err_login' => 'เข้าสู่ระบบไม่สำเร็จ',
    'auth.err_rate' => 'พยายามมากเกินไป',

    'a.new' => 'ใหม่',
    'a.newcat' => 'หมวดหมู่ใหม่',
    'a.name' => 'ชื่อ',
    'a.unit' => 'หน่วย',
    'a.field' => 'ฟิลด์',
    'a.records' => 'รายการ',
    'a.series' => 'ค่าที่วัด',
    'a.value' => 'ค่า',
    'a.time' => 'เวลา',
    'a.save' => 'บันทึก',
    'a.delete' => 'ลบ',
    'a.archive' => 'เก่า',
    'a.restore' => 'ใช้งาน',
    'a.old' => 'เก่า',
    'a.back' => 'กลับ',
    'a.saved' => 'บันทึกแล้ว',
    'a.empty' => 'ว่าง',
    'a.delcat' => 'ลบหมวดหมู่',

    's.latest' => 'ล่าสุด',
    's.avg' => 'เฉลี่ย',
    's.min' => 'ต่ำสุด',
    's.max' => 'สูงสุด',

    'd.token_once' => 'โทเคนแสดงเพียงครั้งเดียว',
    'd.current' => 'อุปกรณ์นี้',
    'd.apikey' => 'คีย์ API',

    'st.pw_old' => 'รหัสผ่านปัจจุบัน',
    'st.pw_new' => 'รหัสผ่านใหม่',

    'i.title' => 'ติดตั้งเป็นแอป',
    'i.ios_1' => 'Safari: แตะแชร์',
    'i.ios_2' => '"เพิ่มไปยังหน้าจอโฮม"',
    'i.ios_3' => 'เปิดจากหน้าจอโฮม',
    'i.android_1' => 'Chrome: แตะเมนู ⋮',
    'i.android_2' => '"ติดตั้งแอป"',
    'i.android_3' => 'เปิดจากหน้าจอหลัก',
    'i.other' => 'เปิดบนมือถือแล้วเพิ่มไปยังหน้าจอโฮม',

    'ft.text' => 'ข้อความ',
    'ft.number' => 'ตัวเลข',
    'ft.date' => 'วันที่',
    'ft.phone' => 'โทรศัพท์',
    'ft.note' => 'บันทึก',

    'cat.profile' => 'โปรไฟล์',
    'cat.people' => 'ผู้คน',
    'cat.phones' => 'เบอร์',
    'cat.heart' => 'หัวใจ',
    'cat.weight' => 'น้ำหนัก',
    'cat.height' => 'ส่วนสูง',
    'cat.steps' => 'ก้าว',
    'cat.sleep' => 'นอน',
    'cat.temp' => 'อุณหภูมิ',
    'cat.medical' => 'การแพทย์',
    'cat.documents' => 'เอกสาร',
    'cat.notes' => 'โน้ต',
    'cat.custom' => 'หมวดหมู่',

    'f.name' => 'ชื่อ',
    'f.birthdate' => 'วันเกิด',
    'f.blood' => 'กรุ๊ปเลือด',
    'f.relation' => 'ความสัมพันธ์',
    'f.number' => 'หมายเลข',
    'f.label' => 'ป้าย',
    'f.date' => 'วันที่',
    'f.note' => 'บันทึก',
    'f.title' => 'หัวข้อ',

    'err.name' => 'ชื่อไม่ถูกต้อง',
    'err.kind' => 'ประเภทไม่ถูกต้อง',
    'err.fields' => 'ขาดฟิลด์',
    'err.value' => 'ค่าไม่ถูกต้อง',
    'err.date' => 'วันที่ไม่ถูกต้อง',
    'err.empty' => 'ว่าง',
];
