<?php
return [
    'nav.devices' => 'อุปกรณ์',
    'nav.settings' => 'ตั้งค่า',
    'nav.logout' => 'ออกจากระบบ',

    'auth.username' => 'ชื่อผู้ใช้',
    'auth.password' => 'รหัสผ่าน',
    'auth.login' => 'เข้าสู่ระบบ',
    'auth.register' => 'สมัครสมาชิก',
    'auth.device_login' => 'เข้าสู่ระบบด้วยอุปกรณ์ …',
    'auth.err_username' => 'ชื่อผู้ใช้ไม่ถูกต้อง (3–32: a–z 0–9 . _ -)',
    'auth.err_password' => 'รหัสผ่านสั้นเกินไป (อย่างน้อย 10)',
    'auth.err_exists' => 'ชื่อนี้ถูกใช้แล้ว',
    'auth.err_server' => 'ข้อผิดพลาดภายใน',
    'auth.err_login' => 'เข้าสู่ระบบไม่สำเร็จ',
    'auth.err_rate' => 'พยายามมากเกินไป',

    'g.contacts' => 'ผู้ติดต่อ',
    'g.health' => 'สุขภาพ',
    'g.security' => 'ความปลอดภัย',
    'g.misc' => 'อื่นๆ',

    'cat.contacts' => 'ผู้ติดต่อ',
    'cat.phones' => 'เบอร์',
    'cat.heart' => 'หัวใจ',
    'cat.weight' => 'น้ำหนัก',
    'cat.height' => 'ส่วนสูง',
    'cat.steps' => 'ก้าว',
    'cat.sleep' => 'นอน',
    'cat.temp' => 'อุณหภูมิ',
    'cat.medical' => 'การแพทย์',
    'cat.passwords' => 'รหัสผ่าน',
    'cat.certs' => 'ใบอนุญาต',
    'cat.serials' => 'ซีเรียล',
    'cat.documents' => 'เอกสาร',
    'cat.notes' => 'โน้ต',

    'f.name' => 'ชื่อ',
    'f.relation' => 'ความสัมพันธ์',
    'f.birthdate' => 'วันเกิด',
    'f.number' => 'หมายเลข',
    'f.blood' => 'กรุ๊ปเลือด',
    'f.note' => 'บันทึก',
    'f.label' => 'ป้าย',
    'f.date' => 'วันที่',
    'f.service' => 'บริการ',
    'f.username' => 'ชื่อผู้ใช้',
    'f.password' => 'รหัสผ่าน',
    'f.mfa' => 'MFA/2FA',
    'f.device' => 'อุปกรณ์',
    'f.serial' => 'หมายเลขซีเรียล',
    'f.title' => 'หัวข้อ',

    'a.new' => 'ใหม่',
    'a.value' => 'ค่า',
    'a.save' => 'บันทึก',
    'a.delete' => 'ลบ',
    'a.archive' => 'เก่า',
    'a.restore' => 'ใช้งาน',
    'a.old' => 'เก่า',
    'a.me' => 'ฉัน',
    'a.back' => 'กลับ',
    'a.saved' => 'บันทึกแล้ว',
    'a.empty' => 'ว่าง',
    'a.name' => 'ชื่อ',

    's.latest' => 'ล่าสุด',
    's.avg' => 'เฉลี่ย',
    's.min' => 'ต่ำสุด',
    's.max' => 'สูงสุด',

    'd.token_once' => 'โทเคนแสดงเพียงครั้งเดียว',
    'd.current' => 'อุปกรณ์นี้',
    'd.apikey' => 'คีย์ API',

    'st.pw_old' => 'รหัสผ่านปัจจุบัน',
    'st.pw_new' => 'รหัสผ่านใหม่',

    'i.title' => 'ติดตั้งเป็นแอป',
    'i.ios_1' => 'Safari: แตะแชร์',
    'i.ios_2' => '"เพิ่มไปยังหน้าจอโฮม"',
    'i.ios_3' => 'เปิดจากหน้าจอโฮม',
    'i.android_1' => 'Chrome: แตะเมนู ⋮',
    'i.android_2' => '"ติดตั้งแอป"',
    'i.android_3' => 'เปิดจากหน้าจอหลัก',
    'i.other' => 'เปิดบนมือถือแล้วเพิ่มไปยังหน้าจอโฮม',

    'err.value' => 'ค่าไม่ถูกต้อง',
    'err.date' => 'วันที่ไม่ถูกต้อง',
    'err.empty' => 'ว่าง',
    'a.edit' => 'แก้ไข',
    'a.cancel' => 'ยกเลิก',
    'a.search' => 'ค้นหา',
    'a.copy' => 'คัดลอก',
    'a.sure' => 'ยืนยันการลบ?',
    'r.7' => '7ว',
    'r.30' => '30ว',
    'r.90' => '90ว',
    'r.365' => '1ปี',
    'r.all' => 'ทั้งหมด',
    'r.empty' => 'ไม่มีค่าในช่วงนี้',
    'st.export' => 'ส่งออกข้อมูล',
    'st.import' => 'นำเข้า',
    'st.import_sure' => 'แทนที่ข้อมูลทั้งหมดด้วยไฟล์นี้?',
    'err.import' => 'ไฟล์ไม่ถูกต้อง',
    'i.continue' => 'ใช้งานต่อในเบราว์เซอร์',
];
